/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#005048",
        surface: "#f8f9fa",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "on-error": "#ffffff",
        "on-tertiary-container": "#c3ffbb",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#dee0ff",
        "secondary-fixed": "#85f6e5",
        "on-background": "#191c1d",
        error: "#ba1a1a",
        background: "#f8f9fa",
        "on-secondary-fixed": "#00201c",
        "primary-fixed-dim": "#bac3ff",
        "primary-container": "#5365c9",
        "surface-variant": "#e1e3e4",
        "surface-tint": "#4355b9",
        "on-primary-container": "#efefff",
        "surface-container": "#edeeef",
        tertiary: "#006318",
        "on-primary-fixed-variant": "#293ca0",
        "tertiary-container": "#107e26",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f0f1f2",
        "on-secondary-container": "#007166",
        secondary: "#006a60",
        "on-primary-fixed": "#00105c",
        "secondary-fixed-dim": "#67d9c9",
        "on-tertiary-fixed-variant": "#005313",
        "on-surface": "#191c1d",
        "inverse-primary": "#bac3ff",
        "tertiary-fixed": "#94f990",
        "on-tertiary-fixed": "#002204",
        "inverse-surface": "#2e3132",
        "tertiary-fixed-dim": "#78dc77",
        "secondary-container": "#85f6e5",
        "outline-variant": "#c4c5d9",
        "error-container": "#ffdad6",
        "on-surface-variant": "#434656",
        "surface-container-high": "#e7e8e9",
        primary: "#394baf",
        outline: "#747688",
        "surface-container-low": "#f3f4f5",
        "surface-bright": "#f8f9fa",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-dim": "#d9dadb",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        ambient: "0 8px 32px rgba(25, 28, 29, 0.06)",
        float: "0 32px 64px -12px rgba(25, 28, 29, 0.06)",
      },
    },
  },
  plugins: [],
};
